"""Reprocessing endpoints: bring existing inspections onto the corrected pipeline.

* A single record can be regenerated by any user who may run the pipeline (``inspections.manage``).
* The bulk legacy migration rewrites many records at once, so it is gated on the administrative
  capability (``users.manage``) and runs on a background worker with polled progress.
* Revision history (the BEFORE / AFTER of each regeneration) is readable by anyone who may read the
  inspection, and is organization-scoped exactly like the inspection itself.
"""
from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy.orm import Session

from backend.api.deps import require_permission
from backend.api.repository import _scoped_inspection
from backend.authz import Permission
from backend.database import get_db
from backend.models import User
from backend.services import reprocess_service

router = APIRouter(prefix="/reprocess", tags=["reprocess"])

MAX_REASON_CHARS = 300


class ReprocessIn(BaseModel):
    reason: str = ""
    # Re-read the stored package images with the recogniser instead of reusing the stored OCR
    # evidence. Slower, and only useful when the OCR engine itself changed.
    refresh_ocr: bool = False


class BatchIn(BaseModel):
    reason: str = ""
    ids: list[int] | None = None
    limit: int = reprocess_service.MAX_BATCH
    refresh_ocr: bool = False


@router.get("/preview")
def preview(
    user: User = Depends(require_permission(Permission.INSPECTIONS_MANAGE)),
    db: Session = Depends(get_db),
):
    """What a migration would touch: engine stamp, counts and the records still on an old engine."""
    return reprocess_service.legacy_preview(db)


@router.post("/batch")
def start_batch(
    body: BatchIn,
    user: User = Depends(require_permission(Permission.USERS_MANAGE)),
):
    """Start the bulk legacy migration (one run at a time) and return its job."""
    if len(body.reason) > MAX_REASON_CHARS:
        raise HTTPException(422, f"Please keep the reason under {MAX_REASON_CHARS} characters.")
    try:
        return reprocess_service.start_migration(
            actor=user.username,
            reason=(body.reason or "bulk reprocessing of legacy inspections").strip(),
            ids=body.ids,
            limit=body.limit,
            refresh_ocr=body.refresh_ocr,
        )
    except reprocess_service.MigrationInProgress as exc:
        raise HTTPException(409, f"A migration is already running ({exc.job_id}).") from exc


@router.get("/jobs")
def jobs(
    user: User = Depends(require_permission(Permission.INSPECTIONS_MANAGE)),
):
    """Recent migration runs in this server process (empty after a restart; revisions persist)."""
    return {"jobs": reprocess_service.recent_jobs()}


@router.get("/jobs/{job_id}")
def job(
    job_id: str,
    user: User = Depends(require_permission(Permission.INSPECTIONS_MANAGE)),
):
    found = reprocess_service.migration_job(job_id)
    if found is None:
        raise HTTPException(404, "Migration job not found in this server process.")
    return found


@router.post("/inspections/{inspection_id}")
def reprocess_one(
    inspection_id: int,
    body: ReprocessIn,
    user: User = Depends(require_permission(Permission.INSPECTIONS_MANAGE)),
    db: Session = Depends(get_db),
):
    """Regenerate ONE inspection in place, keeping the previous result on a revision row."""
    if len(body.reason) > MAX_REASON_CHARS:
        raise HTTPException(422, f"Please keep the reason under {MAX_REASON_CHARS} characters.")
    inspection = _scoped_inspection(db, inspection_id, user)
    if inspection.status == "PROCESSING":
        raise HTTPException(409, "This inspection is currently being processed — try again once it finishes.")
    result = reprocess_service.reprocess_inspection(
        db,
        inspection,
        actor=user.username,
        reason=(body.reason or "manual reprocess").strip(),
        refresh_ocr=body.refresh_ocr,
    )
    return result


@router.get("/inspections/{inspection_id}/revisions")
def revisions(
    inspection_id: int,
    user: User = Depends(require_permission(Permission.INSPECTIONS_VIEW)),
    db: Session = Depends(get_db),
):
    """Every reprocessing event on this inspection, newest first, with BEFORE / AFTER snapshots."""
    _scoped_inspection(db, inspection_id, user)
    return {
        "inspection_id": inspection_id,
        "revisions": reprocess_service.revisions_for(db, inspection_id),
    }
