"""On-device vision package: the always-available second perception source.

`backend.ai` is the OPTIONAL third-party provider; this package is the part that always runs.
"""
from __future__ import annotations

from backend.vision.engine import (  # noqa: F401
    ENGINE_LABEL,
    ENGINE_NAME,
    ENGINE_VERSION,
    KIND_LEGIBILITY,
    KIND_PANEL,
    KIND_SYMBOL,
    KIND_TEXT_BLOCK,
    MARGINAL,
    READABLE,
    STATUS_COMPLETED,
    STATUS_COMPLETED_WITH_PROVIDER,
    STATUS_FAILED,
    STATUS_PROVIDER_FALLBACK,
    STATUS_PROVIDER_NOT_CONFIGURED,
    UNREADABLE,
    ImageVision,
    Region,
    VisionResult,
    analyse_all,
    analyse_image,
    availability_reason,
    available,
    bbox_str,
    fact_rows,
    finish_all,
    finish_image,
    hero_by_image,
    hero_note_for,
    panel_facts,
    parse_bbox,
    prepare_all,
    prepare_image,
    status_for,
    status_text,
    summarise,
)

__all__ = [
    "ENGINE_LABEL",
    "ENGINE_NAME",
    "ENGINE_VERSION",
    "KIND_LEGIBILITY",
    "KIND_PANEL",
    "KIND_SYMBOL",
    "KIND_TEXT_BLOCK",
    "MARGINAL",
    "READABLE",
    "STATUS_COMPLETED",
    "STATUS_COMPLETED_WITH_PROVIDER",
    "STATUS_FAILED",
    "STATUS_PROVIDER_FALLBACK",
    "STATUS_PROVIDER_NOT_CONFIGURED",
    "UNREADABLE",
    "ImageVision",
    "Region",
    "VisionResult",
    "analyse_all",
    "analyse_image",
    "availability_reason",
    "available",
    "bbox_str",
    "fact_rows",
    "finish_all",
    "finish_image",
    "hero_by_image",
    "hero_note_for",
    "panel_facts",
    "parse_bbox",
    "prepare_all",
    "prepare_image",
    "status_for",
    "status_text",
    "summarise",
]
