import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { api } from '../services/api'
import { Card } from '../components/Badges'
import { EmptyState, Skeleton } from '../components/ui'
import type { ReportRow } from '../types'

export default function Reports() {
  const [items, setItems] = useState<ReportRow[]>([])
  const [error, setError] = useState('')
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    api
      .get<{ items: ReportRow[] }>('/reports')
      .then((d) => setItems(d.items))
      .catch((e) => setError(e instanceof Error ? e.message : 'Load failed'))
      .finally(() => setLoading(false))
  }, [])

  return (
    <>
      <div className="page-title">Reports</div>
      <div className="page-sub">Generated PDF inspection reports. Generate new reports from an inspection page.</div>
      {error && <div className="alert error">{error}</div>}
      {loading ? (
        <Card><Skeleton lines={5} /></Card>
      ) : (
      <Card>
        <table className="tbl">
          <thead>
            <tr><th>Report</th><th>Inspection</th><th>Format</th><th>Generated by</th><th>Date</th><th></th></tr>
          </thead>
          {/* tbody children are one expression: a bare text node between JSX rows is invalid
              HTML and React logs a nesting warning for it. */}
          <tbody>{items.length === 0 ? (
            <tr><td colSpan={6}>
              <EmptyState
                headline="No reports yet"
                how="Open an inspection and click “Generate PDF report” to create the first one."
              />
            </td></tr>
          ) : items.map((r) => (
            <tr key={r.id}>
              <td>#{r.id}</td>
              <td><Link to={`/inspections/${r.inspection_id}`}>{r.inspection_number}</Link></td>
              <td>{r.format.toUpperCase()}</td>
              <td>{r.generated_by}</td>
              <td>{r.created_at.slice(0, 19).replace('T', ' ')}</td>
              <td><a href={api.fileUrl('reports', r.stored_filename)} target="_blank" rel="noreferrer">Download</a></td>
            </tr>
          ))}</tbody>
          </table>
          </Card>
      )}
    </>
  )
}
